import { useState } from "react";
import { Link } from "wouter";
import { ArrowRight, ArrowUpRight, CalendarDays, Check, Circle, Phone, Mail, Plus, Wrench, Clock, MessageSquare, BarChart3, CheckCircle2 } from "lucide-react";
import { useReadiness } from "@/lib/readinessApi";
import { useAppointmentRequests, useAvailabilityConfig } from "@/hooks/useAvailability";
import { useInquiries } from "@/hooks/useInquiries";
import { useRealCallsList } from "@/hooks/useVoiceCalls";
import { useDashboardSummary } from "@/components/dashboard/DashboardPanel";
import { typeName, requestStateLabel } from "@/pages/appointments/appointmentsContract";

function dayKey(iso:string,zone:string){return new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:zone}).format(new Date(iso));}
function clock(iso:string,zone:string){return new Date(iso).toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit",timeZone:zone});}
export default function ClarityOverview(){
 const readiness=useReadiness(),appointments=useAppointmentRequests(),config=useAvailabilityConfig(),messages=useInquiries("all"),calls=useRealCallsList(),summary=useDashboardSummary();
 const [days,setDays]=useState(14);
 const zone=config.data?.config.timezone||"UTC";
 const rows=appointments.data?.items??[];
 const pending=rows.filter(r=>["pending_review","requested","held"].includes(r.state));
 const outstanding=(messages.data?.items??[]).filter(m=>m.followUpStatus!=="resolved");
 const today=rows.filter(r=>r.state==="booked"&&dayKey(r.startUtc,zone)===dayKey(new Date().toISOString(),zone)).sort((a,b)=>Date.parse(a.startUtc)-Date.parse(b.startUtc));
 const recent=(calls.data?.items??[]).slice(0,4);
 const trend=(summary.data?.trend??[]).slice(-days);
 const total=trend.reduce((n,d)=>n+d.telephone+d.browser+(d.other??0),0);
 const max=Math.max(1,...trend.map(d=>d.telephone+d.browser+(d.other??0)));
 const phone=trend.reduce((n,d)=>n+d.telephone,0),browser=trend.reduce((n,d)=>n+d.browser,0),other=total-phone-browser;
 const count=pending.length+outstanding.length;
 const r=readiness.data;
 return <div className="cl-overview">
  <div className="cl-page-heading"><h1>Your day, at a glance</h1><p>Manage calls, messages, and appointments — all in one place.</p></div>
  <section className="cl-setup-strip" aria-label="Setup progress"><span className="cl-round"><Wrench size={22}/></span><div className="cl-setup-intro"><strong>{r?.state==="live_call_verified"?"Your receptionist is ready":r?.label||"Checking your setup"}</strong><small>{r?.state==="live_call_verified"?"Keep an eye on your activity and next steps.":"Complete a few quick steps to get the most out of your AI receptionist."}</small></div><div className="cl-setup-steps">{(r?.steps??[]).slice(0,3).map(s=><Link key={s.key} href="/setup"><span className={s.state==="done"?"cl-step-done":"cl-step-open"}>{s.state==="done"?<Check size={17}/>:<Circle size={24}/>}</span><span><strong>{s.title}</strong><small>{s.state==="done"?"Completed":`${s.checks.filter(c=>c.state!=="done"&&c.state!=="off").length} checks left`}</small></span></Link>)}</div><Link className="cl-button" href={r?.next?.path||"/setup"}>{r?.state==="live_call_verified"?"View setup":"Finish setup"}<ArrowRight size={18}/></Link></section>
  <div className="cl-overview-grid">
   <section className="cl-card" id="attention"><div className="cl-card-heading"><h2>Needs your attention {count>0&&<span className="cl-count">{count}</span>}</h2><Link href="/activity/inquiries">View all</Link></div>
    {(appointments.isError||messages.isError)&&<p role="alert" className="cl-empty">Some items could not be loaded. <button onClick={()=>{void appointments.refetch();void messages.refetch();}}>Try again</button></p>}
    {pending.slice(0,1).map(a=><article className="cl-attention-row" key={a.id}><span className="cl-round"><CalendarDays size={25}/></span><div><h3>New booking request</h3><p>{a.contact?.name||"New caller"} <span>·</span> {a.contact?.phone||a.contact?.email||"Contact not provided"}</p><p>{typeName(config.data?.config,a.appointmentTypeId)} · {new Date(a.startUtc).toLocaleString("en-US",{timeZone:zone,month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</p><div className="cl-tags"><span className="cl-pill">New request</span><span className="cl-pill cl-pill--neutral">Appointment</span></div></div><Link className="cl-button" href={`/scheduling/appointments?id=${encodeURIComponent(a.id)}`}>Review request</Link></article>)}
    {outstanding.slice(0,pending.length?1:2).map(m=><article className="cl-attention-row" key={m.id}><span className="cl-round cl-round--blue"><Mail size={25}/></span><div><h3>{m.topic||"New message"}</h3><p>{m.callerName} <span>·</span> {m.callbackPhone||"Message captured"}</p><p className="cl-clamp">{m.details}</p><div className="cl-tags"><span className="cl-pill cl-pill--blue">Message</span><span className="cl-pill cl-pill--neutral">{m.urgency==="urgent"?"Urgent":"General inquiry"}</span></div></div><Link className="cl-button cl-button--outline" href={`/activity/inquiries?id=${m.id}`}>Open message</Link></article>)}
    {!count&&!appointments.isError&&!messages.isError&&<div className="cl-empty"><CheckCircle2 size={30}/><h3>{appointments.isLoading||messages.isLoading?"Loading your next steps…":"You're all caught up"}</h3><p>New booking requests and caller messages will appear here.</p></div>}
   </section>
   <section className="cl-card"><div className="cl-card-heading"><h2><CalendarDays className="cl-blue" size={24}/>Today’s appointments</h2><Link href="/scheduling/appointments">View calendar</Link></div><div className="cl-agenda">{today.slice(0,4).map(a=><Link href={`/scheduling/appointments?id=${encodeURIComponent(a.id)}`} key={a.id} className="cl-agenda-row"><span className="cl-agenda-time">{clock(a.startUtc,zone)}</span><span><strong>{typeName(config.data?.config,a.appointmentTypeId)}</strong><small>{a.contact?.name||"Appointment"}</small></span><span className="cl-pill">Confirmed</span></Link>)}{!today.length&&<div className="cl-empty"><CalendarDays size={28}/><p>{appointments.isLoading?"Loading appointments…":appointments.isError?"Appointments could not be loaded.":"No confirmed appointments today."}</p><small>Times shown in {zone}.</small></div>}</div><Link href="/scheduling/appointments?add=1" className="cl-add"><Plus size={21}/>Add appointment</Link></section>
  </div>
  <div className="cl-analytics-heading"><div><h2>Your business, in perspective</h2><p>Activity and trends from your receptionist.</p></div><select aria-label="Chart period" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={14}>Last 14 days</option><option value={7}>Last 7 days</option></select></div>
  <div className="cl-metrics">{(summary.data?.cards??[{key:"calls",label:"Calls today",value:null,detail:"Waiting for activity data",href:"/activity/calls"},{key:"messages",label:"Messages",value:null,detail:"Waiting for activity data",href:"/activity/inquiries"},{key:"bookings",label:"Appointments",value:null,detail:"Waiting for activity data",href:"/scheduling/appointments"}]).map((c,i)=><Link className="cl-card cl-metric" key={c.key} href={c.href}><span className={`cl-round ${i%2?"cl-round--blue":""}`}>{i%3===0?<Phone size={21}/>:i%3===1?<MessageSquare size={21}/>:<CalendarDays size={21}/>}</span><div><p>{c.label}</p><strong>{c.value??"—"}</strong><small>{c.detail}</small></div><ArrowUpRight size={18}/></Link>)}</div>
  <div className="cl-charts"><section className="cl-card"><div className="cl-card-heading"><h2><BarChart3 size={22}/>Call activity</h2><span className="cl-muted">{total} recorded · {days} days</span></div>{summary.isError?<p className="cl-empty">Activity could not be loaded. <button onClick={()=>void summary.refetch()}>Try again</button></p>:<><div className="cl-bar-chart" role="img" aria-label={`Daily call activity, ${total} calls in the displayed period`}>{trend.map(t=><div className="cl-bar-column" key={t.date}><div className="cl-bar-track"><div className="cl-bar" style={{height:`${(t.telephone+t.browser+(t.other??0))/max*100}%`}} title={`${t.date}: ${t.telephone} phone, ${t.browser} browser, ${t.other??0} other calls`}/></div><small>{new Date(t.date+"T12:00:00Z").toLocaleDateString("en-US",{day:"numeric",month:"short",timeZone:"UTC"})}</small></div>)}</div>{!trend.length&&<p className="cl-empty">A daily trend appears as call activity is recorded.</p>}<details className="cl-chart-data"><summary>View chart data</summary><ul>{trend.map(t=><li key={t.date}>{t.date}: {t.telephone} phone · {t.browser} browser · {t.other??0} other</li>)}</ul></details></>}</section><section className="cl-card"><div className="cl-card-heading"><h2><Clock size={22}/>Call sources</h2></div><div className="cl-donut-area"><div className="cl-donut" style={{background:total?`conic-gradient(#007d68 0 ${phone/total*100}%, #3679f5 ${phone/total*100}% ${(phone+browser)/total*100}%, #adcbd3 ${(phone+browser)/total*100}% 100%)`:"#e8efef"}}><div><strong>{summary.isError?"—":total}</strong><small>calls</small></div></div><ul className="cl-chart-legend"><li><i/>{phone} Phone calls</li><li><i/>{browser} Browser tests</li><li><i/>{other} Other / unknown</li></ul></div><p className="cl-muted">Based on recorded call sources, not an estimate of business performance.</p></section></div>
  <section className="cl-card cl-outcomes"><div className="cl-card-heading"><div><h2><Phone size={24}/>Recent call outcomes</h2><p>A record of recent calls handled by your AI receptionist.</p></div><Link href="/activity/calls">View all calls <ArrowRight size={17}/></Link></div><div className="cl-table-wrap"><table><thead><tr><th>Time</th><th>Caller</th><th>Outcome</th><th>Summary</th><th><span className="sd-sr">Open record</span></th></tr></thead><tbody>{recent.map(c=><tr key={c.callId}><td>{new Date(c.startedAt).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:zone})}</td><td>{c.callerNumberDisplay||"Unknown caller"}</td><td><span className={`cl-pill ${c.state==="completed"?"":"cl-pill--blue"}`}>{c.stateLabel}</span></td><td>{c.summary||"Open the call to review its available details."}</td><td><Link href={`/activity/calls/${encodeURIComponent(c.callId)}`} aria-label={`Open call from ${c.callerNumberDisplay||"unknown caller"}`}><ArrowUpRight size={20}/></Link></td></tr>)}</tbody></table></div>{!recent.length&&<p className="cl-empty">{calls.isLoading?"Loading recent calls…":calls.isError?"Call records couldn't be loaded.":"No calls yet. Your call outcomes will appear here after activation."}</p>}</section>
 </div>;
}
