import { Router, type IRouter } from "express";
import healthRouter from "./health";
import discoveryRouter from "./discovery";
import discoveryV1Router from "./discoveryV1";
import adminRouter from "./admin";
import contactRouter from "./contact";
import crmRouter from "./crm";
import crmProjectsRouter from "./crmProjects";
import crmDiscoveryRouter from "./crmDiscovery";
import phoneRouter from "./phone";
import copilotRouter from "./copilot";
import aiCampaignGenerateRouter from "./aiCampaignGenerate";
import aiToolkitRouter from "./aiToolkit";
import landingTestRouter from "./landingTest";
import intakeAgentRouter from "./intakeAgent";
import receptionistAuthRouter from "./receptionistAuth";
import receptionistConversationsRouter from "./receptionistConversations";
import receptionistAdminRouter from "./receptionistAdmin";
import receptionistBillingRouter from "./receptionistBilling";
import receptionistAgentConfigRouter from "./receptionistAgentConfig";
import receptionistVoiceAssistantsRouter from "./receptionistVoiceAssistants";
import receptionistVoiceWebhookRouter from "./receptionistVoiceWebhook";
import receptionistVoiceCallsRouter from "./receptionistVoiceCalls";
import receptionistAvailabilityRouter from "./receptionistAvailability";
import receptionistCalendarRouter from "./receptionistCalendar";
import voiceSmsWebhookRouter from "./voiceSmsWebhook";
import receptionistNumbersRouter from "./receptionistNumbers";
import receptionistMonitoringRouter from "./receptionistMonitoring";
import monitoringRouter from "./monitoring";
import receptionistAccountRouter from "./receptionistAccount";
import adminVoiceDiagnosticsRouter from "./adminVoiceDiagnostics";
import voiceBillingWebhookRouter from "./voiceBillingWebhook";
import publicSchedulingRouter from "./publicScheduling";
import helpdeskRouter from "./helpdesk";
import receptionistOnboardingRouter from "./receptionistOnboarding";
import receptionistContactsRouter from "./receptionistContacts";
import receptionistInvitesRouter from "./receptionistInvites";
import publicBetaRequestsRouter from "./publicBetaRequests";
import publicDemoRouter from "./publicDemo";
import adminVoiceIssuesRouter from "./adminVoiceIssues";

const router: IRouter = Router();

router.use(healthRouter);
router.use(discoveryRouter);
router.use(discoveryV1Router);
router.use(adminRouter);
router.use(contactRouter);
router.use(crmRouter);
router.use(crmProjectsRouter);
router.use(crmDiscoveryRouter);
router.use(phoneRouter);
router.use(copilotRouter);
router.use(aiCampaignGenerateRouter);
router.use(aiToolkitRouter);
router.use(landingTestRouter);
router.use(intakeAgentRouter);
router.use(receptionistAuthRouter);
router.use(receptionistConversationsRouter);
router.use(receptionistAdminRouter);
router.use(receptionistBillingRouter);
router.use(receptionistAgentConfigRouter);
router.use(receptionistVoiceAssistantsRouter);
router.use(receptionistVoiceWebhookRouter);
router.use(receptionistVoiceCallsRouter);
router.use(receptionistAvailabilityRouter);
router.use(receptionistCalendarRouter);
router.use(voiceSmsWebhookRouter);
router.use(receptionistNumbersRouter);
router.use(receptionistMonitoringRouter);
router.use(monitoringRouter);
router.use(receptionistAccountRouter);
router.use(adminVoiceDiagnosticsRouter);
router.use(voiceBillingWebhookRouter);
router.use(publicSchedulingRouter);
router.use(helpdeskRouter);
router.use(receptionistOnboardingRouter);
router.use(receptionistContactsRouter);
router.use(receptionistInvitesRouter);
router.use(publicBetaRequestsRouter);
router.use(publicDemoRouter);
router.use(adminVoiceIssuesRouter);

export default router;
