// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/helpdesk/Inbox.tsx": () => import("../components/mockups/helpdesk/Inbox.tsx"),
  "./components/mockups/hero-variants/GoldAccent.tsx": () => import("../components/mockups/hero-variants/GoldAccent.tsx"),
  "./components/mockups/hero-variants/PureMinimal.tsx": () => import("../components/mockups/hero-variants/PureMinimal.tsx"),
  "./components/mockups/hero-variants/SoftBlue.tsx": () => import("../components/mockups/hero-variants/SoftBlue.tsx")
};
