-- MANUAL ROLLBACK ONLY. Not part of the automatic Drizzle migration journal
-- and never applied by `drizzle-kit migrate`. Do not wire this file into any
-- automated process.
--
-- Rolls back migration: lib/db/drizzle/voice/0007_<tag>.sql
-- (V5 private beta: persistent onboarding progress, public beta-access
-- requests, and invite-only signup codes). The forward migration is
-- GENERATED by the lead with `pnpm --filter @workspace/db run generate:voice`
-- from the schema files in lib/db/src/schema/voice/ — it is never
-- hand-written, so this rollback names the tables, not a drizzle tag.
-- Rename this file to match the generated tag (`0007_<tag>_rollback.sql`)
-- when the forward file exists; the content does not change.
--
-- Run only by an operator, deliberately, and only after confirming the
-- target database. It does not remove this migration's row from
-- `drizzle.__drizzle_migrations_voice`; clear that row separately before
-- the forward migration can be applied again.
--
-- VERIFY BACKUPS FIRST.
--
-- SAFETY GUARD: refuse while any invite has been redeemed (the row is the
-- only record of which code produced which firm — an audit fact), and
-- refuse while any beta request has left the 'new' state (an operator has
-- acted on it; that decision trail must be exported deliberately first).
-- Unredeemed invites and untouched requests are recreatable, so they do
-- not block; onboarding progress is regenerable from the dashboard, so it
-- does not block either.
--
-- LOSS ON ROLLBACK: every firm's onboarding progress (the hub restarts at
-- step one), every pending beta request, and every outstanding invite code
-- (an invitee holding an unredeemed code can no longer sign up until a new
-- one is minted).

BEGIN;

DO $$
DECLARE
  redeemed_invites integer;
  acted_requests integer;
BEGIN
  SELECT count(*) INTO redeemed_invites FROM "voice_invites" WHERE "redeemed_at" IS NOT NULL;
  IF redeemed_invites > 0 THEN
    RAISE EXCEPTION 'Refusing to roll back: % invite(s) have been redeemed (audit fact of which code produced which firm). Export them deliberately first.', redeemed_invites;
  END IF;
  SELECT count(*) INTO acted_requests FROM "voice_beta_requests" WHERE "status" <> 'new';
  IF acted_requests > 0 THEN
    RAISE EXCEPTION 'Refusing to roll back: % beta request(s) are no longer ''new'' (an operator acted on them). Export the decision trail deliberately first.', acted_requests;
  END IF;
END $$;

DROP TABLE IF EXISTS "voice_invites";
DROP TABLE IF EXISTS "voice_beta_requests";
DROP TABLE IF EXISTS "voice_onboarding_states";

COMMIT;
